USE mydb;

DROP PROCEDURE IF EXISTS handlerdemo
DELIMITER //
CREATE PROCEDURE handlerdemo ()
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '23000' SET @x2 = 1;
  SET @x = 1;
  INSERT INTO articulos VALUES (154,"mouse KM-123",200);
  SET @x = 2;
  INSERT INTO articulos VALUES (154,"mouse KM-123",200);
  SET @x = 3;
END //
DELIMITER ;

SET @x = 0, @x2 = 0;
CALL handlerdemo();
SELECT @x, @x2;

DROP PROCEDURE IF EXISTS handInsertar;
DELIMITER //
CREATE PROCEDURE handInsertar(IN ID INT, IN NOMBRE VARCHAR(50), IN PRECIO DOUBLE)
BEGIN
DECLARE continue HANDLER FOR SQLSTATE '23000' SET @ERROR = 1;
SET @ERROR=0;
INSERT INTO articulos VALUES (ID,NOMBRE,PRECIO);
IF @ERROR=1 THEN
SELECT "ERROR, LLAVE DUPLICADA";
END IF;
END //
DELIMITER ;

SELECT * FROM articulos;
CALL handInsertar(1, "Tarjeta Gráfica", 77.77);